-- Module 2 Lab Solution

drop table INSTRUCTOR;

create table INSTRUCTOR (
	INS_ID integer PRIMARY KEY NOT NULL,
	LASTNAME  varchar(50),
	FIRSTNAME varchar(50),
	CITY varchar(50),
	COUNTRY char(2)	
);

INSERT INTO INSTRUCTOR
	(INS_ID, LASTNAME, FIRSTNAME)
VALUES 
	(1,'Ahuja','Rav');


INSERT INTO INSTRUCTOR
	(INS_ID, LASTNAME, FIRSTNAME)
VALUES 
	(2, 'Chong', 'Raul'),
	(3, 'Vasudevan', 'Hima');

SELECT *  from INSTRUCTOR; 

UPDATE INSTRUCTOR
SET CITY = 'TORONTO',
		COUNTRY = 'CA' 
WHERE INS_ID = (1);

UPDATE INSTRUCTOR
SET CITY = 'TORONTO',
		COUNTRY = 'CA' 
WHERE INS_ID = (2);

UPDATE INSTRUCTOR
SET CITY = 'Chicago',
		COUNTRY = 'US'
WHERE INS_ID = 3;	

SELECT FIRSTNAME, LASTNAME, COUNTRY  FROM INSTRUCTOR WHERE CITY = 'TORONTO';

UPDATE INSTRUCTOR
SET CITY = 'Markham'
WHERE FIRSTNAME = 'Rav';

DELETE FROM INSTRUCTOR WHERE FIRSTNAME = 'Raul';
